baseURL = "https://ozansahin.io/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Ozan SAHIN · Personel Blog"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Ozan SAHIN"
  email = "sahinozan@yahoo.com"
  description = "Personel Blog"
  bio = "I'm Software Engineer.\nI like cooking, coffee and camping."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/oznshn"
    linkedin = "https://www.linkedin.com/in/ozan-sahin-b22a8a196/"
    twitter = "https://twitter.com/ozn_shn"